scalaVersion := "2.13.1"
name := "scala-3dcg-linalg"
organization := "info.biacco42"
organizationName := "Biacco42"
version := "0.1.0-SNAPSHOT"
githubOwner := "Biacco42"
githubRepository := "scala-3dcg-linalg"
